director_uuid: (( param "Please set the UUID of your BOSH Director" ))

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-6000000
  max_in_flight: 1
  max_errors: 1

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
  version: latest

name: logsearch

releases:
- {name: logsearch, version: latest}
- {name: logsearch-for-cloudfoundry, version: latest}
- {name: prometheus, version: latest}
- {name: cf, version: latest}
- {name: snort, version: latest}
- {name: cron, version: latest}
